branches:
  except:
    - gh-pages
matrix:
  fast_finish: true
  allow_failures:
    - RUST_CHANNEL: nightly
environment:
  matrix:
    # Earliest compatible stable version
    - TARGET: i686-pc-windows-gnu
      RUST_CHANNEL: 1.0.0
    - TARGET: x86_64-pc-windows-gnu
      RUST_CHANNEL: 1.0.0
    # Stable channel
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: stable
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: stable
    # Beta channel
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: beta
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: beta
    # Nightly channel
    - TARGET: i686-pc-windows-msvc
      RUST_CHANNEL: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_CHANNEL: nightly

# Install Rust and Cargo
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/channel-rust-stable"
  - ps: $env:RUST_VERSION = Get-Content channel-rust-stable | select -first 1 | %{$_.split('-')[1]}
  - if NOT "%RUST_CHANNEL%" == "stable" set RUST_VERSION=%RUST_CHANNEL%
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-${env:RUST_VERSION}-${env:TARGET}.exe"
  - rust-%RUST_VERSION%-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - rustc -V
  - cargo -V

build: false

# Equivalent to Travis' `script` phase
test_script:
  - cargo build
  - cargo test
